general:
  # Commands to run when the WM has started.
  startup_commands:
    - "shell-exec C:\\Users\\ellio\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Discord Inc\\Discord.lnk"
    - "shell-exec C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Steam.lnk"

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: true

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "monitor_focus"

gaps:
  # Gap between adjacent windows.
  inner_gap: "15px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "10px"
    right: "15px"
    bottom: "15px"
    left: "15px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#cba6f7"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: "#6c7086"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "0_main"
    display_name: ""
    keep_alive: true
  - name: "1_social"
    display_name: ""
    keep_alive: true
  - name: "2_games"
    display_name: ""
    keep_alive: true

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

  - commands: ["move --workspace 1_social"]
    match:
      # Moves Discord to workspace social.
      - window_process: { regex: "Discord" }
  - commands: ["move --workspace 2_games"]
    match:
      # Moves Steam to workspace games.
      - window_title: { regex: "Steam" }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

  # When enabled, all keybindings are disabled except for alt+shift+p which
  # returns to default keybindings. 
  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+shift+p"]

keybindings:
  # Close current window
  - commands: ["close"]
    bindings: ["alt+x"]

  # Navigate between workspaces.
  - commands: ["focus --next-workspace"]
    bindings: ["alt+d"]
  - commands: ["focus --prev-workspace"]
    bindings: ["alt+a"]

  # Move windows between workspaces.
  - commands: ["move --next-workspace", "focus --next-workspace"]
    bindings: ["alt+shift+d"]
  - commands: ["move --prev-workspace", "focus --prev-workspace"]
    bindings: ["alt+shift+a"]

  # App shortcuts
  - commands: ["shell-exec explorer"]
    bindings: ["alt+f"] # File Explorer
  - commands: ["shell-exec wt"]
    bindings: ["alt+t"] # Windows Terminal
  - commands: ["shell-exec %APPDATA%\\Microsoft\\Windows\\Start Menu\\NixOS.lnk"]
    bindings: ["alt+shift+t"] # WSL Terminal
  - commands: ["shell-exec %PROGRAMDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Visual Studio Code\\Visual Studio Code.lnk"]
    bindings: ["alt+c"] # VSCode
  - commands: ["shell-exec %PROGRAMDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Zen.lnk"]
    bindings: ["alt+w"] # Zen


  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["alt+r"]

  # Disables all keybindings until alt+shift+p is pressed again.
  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["alt+shift+p"]

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+v"]

  # Change focus from tiling windows -> floating -> fullscreen.
  # - commands: ["wm-cycle-focus"]
  #   bindings: ["alt+space"]

  # Change the focused window to be floating.
  # - commands: ["toggle-floating --centered"]
    # bindings: ["alt+shift+space"]

  # Change the focused window to be tiling.
  # - commands: ["toggle-tiling"]
  #   bindings: ["alt+t"]

  # Change the focused window to be fullscreen.
  # - commands: ["toggle-fullscreen"]
  #   bindings: ["alt+f"]

  # Minimize focused window.
  # - commands: ["toggle-minimized"]
    # bindings: ["alt+m"]

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["alt+shift+e"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["alt+shift+w"]




  # Restart yasb
  - commands: ["shell-exec powershell -Command \"Stop-Process -Name yasb; Start-Process yasb\""]
    bindings: ["alt+shift+b"]
  